### ISSUE TITLE
[Issue] Adding a Pokemon to a gym's pool causes a console error, can't access temp pool Pokemon.

### ISSUE THREAD

**Issue by KorVron** [AnDwHaT5-Sidemods/AGP-Responged#60]
Same as the title, it should be noted that after adding the Pokemon and checking the temporary pool, said Pokemon does not show up.
Using mods:
Pixelmon Reforged 7.0.7
SpongeForge 1.12.3-2825-7.1.6
AGP Responged 1.0.2.

The console errors are below:
[18:32:48] [Server thread/INFO] [nucleus]: ProfRowan ran the command: /addgympoke 1 Grass
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: java.lang.ArrayIndexOutOfBoundsException: 0
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon.func_70037_a(EntityPixelmon.java:518)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1866)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at com.pixelmonmod.pixelmon.config.PixelmonEntityList.createEntityFromNBT(PixelmonEntityList.java:153)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at agp.andwhat5.commands.gyms.AddGymPoke.execute(AddGymPoke.java:37)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at agp.andwhat5.commands.utils.PlayerOnlyCommand.execute(PlayerOnlyCommand.java:21)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[18:32:48] [Server thread/INFO] [STDERR]: [com.pixelmonmod.pixelmon.entities.pixelmon.EntityPixelmon:func_70037_a:533]: 	at java.lang.Thread.run(Thread.java:745)
[18:32:52] [Server thread/INFO] [nucleus]: ProfRowan ran the command: /gympokes grass
[18:32:52] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'gympokes grass' for source EntityPlayerMP['ProfRowan'/11, l='world', x=74.80, y=73.00, z=-265.83]: tried to access field com.pixelmonmod.pixelmon.battles.attacks.Attack.baseAttack from class agp.andwhat5.gui.GymPokemonGui
java.lang.IllegalAccessError: tried to access field com.pixelmonmod.pixelmon.battles.attacks.Attack.baseAttack from class agp.andwhat5.gui.GymPokemonGui
	at agp.andwhat5.gui.GymPokemonGui.getPokemonElement(GymPokemonGui.java:161) ~[GymPokemonGui.class:?]
	at agp.andwhat5.gui.GymPokemonGui.constructGymPokemonPage(GymPokemonGui.java:96) ~[GymPokemonGui.class:?]
	at agp.andwhat5.gui.GymPokemonGui.openGymPokemonGui(GymPokemonGui.java:49) ~[GymPokemonGui.class:?]
	at agp.andwhat5.commands.gyms.GymPokemon.execute(GymPokemon.java:16) ~[GymPokemon.class:?]
	at agp.andwhat5.commands.utils.PlayerOnlyCommand.execute(PlayerOnlyCommand.java:21) ~[PlayerOnlyCommand.class:?]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2825-7.1.6]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2825-7.1.6]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) [SpongeCommandManager.class:1.12.2-2825-7.1.6]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2825-7.1.6]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by Scotford** [comment]
I am currently having the same issue atm, is there anyway to fix this or not atm?  I'm really on getting this error message "Server thread/ERROR [Sponge]: Error occurred while executing command 'gympokemon water' for source EntityPlayerMP['Scotford'/133614, l='world', x=-16889.60, y=67.15, z=2758.19]: tried to access field com.pixelmonmod.pixelmon.battles.attacks.Attack.baseAttack from class agp.andwhat5.gui.GymPokemonGui".

**Comment by LoneWolffy** [comment]
Ya'll should really pick up an updated fork/version from the server owner's or Andwhat5's discord. There's plenty around, just use the discord search function to hunt for files. Otherwise, server owner's discord. 
These have been patched, but no official release has been made due to other underlying features going through rewrites/fixes as well.

**Comment by Scotford** [comment]
> Ya'll should really pick up an updated fork/version from the server owner's or Andwhat5's discord. There's plenty around, just use the discord search function to hunt for files. Otherwise, server owner's discord.
> These have been patched, but no official release has been made due to other underlying features going through rewrites/fixes as well.

Do you know the discord link I can't seem to find the one i'm needing

**Comment by LoneWolffy** [comment]
https://discord.gg/dvGAj7 here's a 1 day duration link

**Comment by Scotford** [comment]
Thank you so much

**Comment by BlackNgeo** [comment]
Hello, I also have the same problem and I need help because I am a server administrator and I need the plugin to work correctly, I have searched, and informed but I do not understand how I have to do to update it, could you help me?
